version: '2'
services:
    agiflex-mysql:
        container_name: agiflex-mysql
        image: mysql:5.7.12
        # volumes:
        #     - ~/volumes/jhipster/agiflex/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=agiflex
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl
